# Start from the latest golang base image
FROM golang:latest

# Add Maintainer Info
LABEL maintainer="tim.huebener@gmail.com"

# Set the Current Working Directory inside the container
WORKDIR /app

# Copy the source from the current directory to the Working Directory inside the container
COPY ../../go.mod .
COPY ../../cmd/stocks-htmx ./cmd/stocks-htmx
COPY ../../pkg ./pkg
COPY ../../web ./web

# Download all dependencies. Dependencies will be cached if the go.mod and go.sum files are not changed
# RUN go mod download

# Set the Current Working Directory inside the container for building the Go app
WORKDIR ./cmd/stocks-htmx/

# Build the Go app
RUN go build -o main .

# Expose port 8080 to the outside world
EXPOSE 8080

# Command to run the executable
CMD ["./main"]