apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-htmx-deployment
  labels:
    app: go-htmx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-htmx
  template:
    metadata:
      labels:
        app: go-htmx
    spec:
      containers:
        - name: go-htmx
          image: timhuebener/go-htmx:latest
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: go-htmx-service
spec:
  selector:
    app: go-htmx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
